### PR TITLE
Ignore limit based on direction

### PR DESCRIPTION
**Pull request by NomarCub**
This makes it so that panes don't expand when making the window narrower, and don't collapse when making the window wider. A potential solution to #2. I also updated the config files to the latest from the Obsidian Sample Plugin.

### CODE REVIEW

**Comment by NomarCub** [comment]
@mybuddymichael if you have the time I'd appreciate if you took a look at this.

**Comment by mybuddymichael** [comment]
There seems to be a decent number of changes that are unrelated to the problem stated in the PR text. As it is, I'm not going to accept this PR in its current form. If you want to reduce the code changes to exactly and only those that solve the problem stated in the PR, I can take a look again. If there are other problems with this repository, I encourage you to make separate PRs for those.

**Comment by NomarCub** [comment]
Hi!
I reduced the code changes.

**Comment by NomarCub** [comment]
@mybuddymichael it's been a while, would you take a look at this?

**Comment by NomarCub** [comment]
@mybuddymichael Please accept this PR. I'm gonna have to make a fork and submit it to community plugins to get this feature otherwise.

**Comment by NomarCub** [comment]
It's been a while. I made a fork that I'm in the process of adding to community plugins here: https://github.com/obsidianmd/obsidian-releases/pull/1063

Would you be open to transfering the existing plugin entry over to my repo? Or adding me as a maintainer to this repo? Or transferring this repo to me? I just want the PR to be available to the public.

**Pull request closed without merging**
